# Generated by Django 5.1.4 on 2024-12-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=50, unique=True)),
                ('color_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('psychological_data', models.JSONField(blank=True, null=True)),
                ('journal_entry', models.TextField(blank=True, null=True)),
                ('mood_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.moodcolors')),
            ],
        ),
    ]
