# Generated by Django 5.1.4 on 2024-12-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='mood_color',
            field=models.CharField(choices=[('#FFFF00', 'Happy'), ('#0000FF', 'Sad'), ('#FF0000', 'Angry'), ('#00FF00', 'Relaxed'), ('#808080', 'Neutral')], default='#808080', max_length=7),
        ),
        migrations.AlterField(
            model_name='days',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.DeleteModel(
            name='MoodColors',
        ),
    ]
