# Generated by Django 5.1.4 on 2024-12-31 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_days_mood_color_alter_days_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='journal_entry',
            new_name='journal_entries',
        ),
        migrations.RemoveField(
            model_name='days',
            name='mood_color',
        ),
        migrations.RemoveField(
            model_name='days',
            name='psychological_data',
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('mood_color', models.CharField(choices=[('#FFFF00', 'Happy'), ('#0000FF', 'Sad'), ('#FF0000', 'Angry'), ('#00FF00', 'Relaxed'), ('#808080', 'Neutral')], default='#808080', max_length=7)),
                ('proper_nutrition', models.BooleanField(default=False)),
                ('proper_hydration', models.BooleanField(default=False)),
                ('hydration_amount', models.FloatField(blank=True, null=True)),
                ('proper_exercise', models.BooleanField(default=False)),
                ('exercise_duration', models.FloatField(blank=True, null=True)),
                ('exercise_description', models.TextField(blank=True, null=True)),
                ('hours_of_sleep', models.FloatField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.days')),
            ],
        ),
    ]
