# Generated by Django 5.1.4 on 2024-12-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_journal_entry_days_journal_entries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='journal_entries',
            new_name='content',
        ),
        migrations.AddField(
            model_name='days',
            name='exercise_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='exercise_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='hours_of_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='hydration_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='mood_color',
            field=models.CharField(choices=[('#FFFF00', 'Happy'), ('#0000FF', 'Sad'), ('#FF0000', 'Angry'), ('#00FF00', 'Relaxed'), ('#808080', 'Neutral')], default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='days',
            name='proper_exercise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='days',
            name='proper_hydration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='days',
            name='proper_nutrition',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
