# Generated by Django 5.1.4 on 2025-01-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_journal_entries_days_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='content',
            new_name='entry_content',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='date',
            new_name='entry_date',
        ),
    ]
